spring:
  application:
    name: farmtofolk-ledger

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/farmtofolk}
    username: ${DB_USERNAME:manasadevaram}
    password: ${DB_PASSWORD:}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      repositories:
        enabled: false

  cache:
    type: redis

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}

    show-sql: ${JPA_SHOW_SQL:true}

    properties:
      hibernate:
        format_sql: ${HIBERNATE_FORMAT_SQL:true}
