spring:
  application:
    name: farmtofolk-ledger

  datasource:
    url: jdbc:postgresql://localhost:5432/farmtofolk
    username: manasadevaram
    password:

  data:
    redis:
      host: localhost
      port: 6379
      repositories:
        enabled: false

  cache:
    type: redis

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true
